;INSTITUTO TECNOLOGICO SUPERIOR DE VALLADOLID
;LENGUAJES Y AUTOMATAS II
;INGENIERIA EN SISTEMAS COMPUTACIONALES
;HECHO POR ROGELIO CANCHE CANCHE
;SEXTO SEMESTRE "A"

.MODEL SMALL
.STACK 100
.DATA
MSJ1 DB 'INGRESE EL PRIMER NUMERO :$'
MSJ2 DB 13,10,'INGRESE EL SEGUNDO NUMERO :$'
MSJ3 DB 13,10, 'SUMA:$'
MSJ4 DB 13,10, 'RESTA:$'
MSJ5 DB 13,10, 'MULTIPLICACION:$'
MSJ6 DB 13,10, 'DIVISION:$'
LINEA DB 13,10, '$'
VAR1 DB 0
VAR2 DB 0
.CODE
.STARTUP

CALL LIMPIA
MOV AH, 09H
LEA DX, MSJ1    ;DESPLEGAR NUMERO 1:
INT 21H

CALL LEER       ;LEE PRIMER NUMERO
MOV AL, 30H      ;RESTAR 30H PARA OBTENER EL NUMEROÇ
MOV VAR1, AL        ;LO GUARDA EN LA VARIABLE1
MOV AH, 09H
LEA DX, MSJ2     ;DESPLIEGA NUMERO 2
INT 21H

CALL LEER       ;LEE EL SEGUNDO NUMERO     
SUB AL, 30H      ;RESTAR 30H PARA OBTENER EL NUMEROÇ
MOV VAR2, AL     ;LO GUARDA EN LA VARIABLE2
MOV BL, VAR2     ;MOVER A BL

;--------SUMA---------------

ADD BL, VAR1
MOV AH,09H
LEA DX, MSJ3  ;IMPRIMIR SUMA
INT 21H

MOV DL,BL   ;SE PONE EN DL EL NUMERO A IMPRIMI
ADD DL,30H  ;AGREGA 30H PARA OBTENER EL CARACTER
MOV AH,02H  ;IMPRIME UN CARACTER
INT 21H

;------RESTA--------------

MOV BL, VAR1
SUB BL, VAR2
MOV AH, 09H
LEA DX, MSJ4
INT 21H
MOV DL, BL
ADD DL, 30H
MOV AH, 02H
INT 21H

;------MULTIPLICACION------

MOV AH, 09H
LEA DX, MSJ5
INT 21H

MOV AL, VAR1
MOV BL, VAR2
MUL BL     ;MULT AL=AL*BL
MOV DL,AL  ;MOVER AL A DL PARA IMPRIMIR
ADD DL, 30H
MOV AH,02H
INT 21H

;--------DIVISION--------

MOV AH, 09H
LEA DX, MSJ6
INT 21H

XOR AX,AX  ;SE LIMPIA EL REGISTRO AX
MOV AL, VAR2
MOV BL, AL 
MOV AL, VAR1
DIV BL    ;DIVIDE EL AX/BX Y EL RESULTADO LO ALMACENA EN DX Y EL RESIDUO QUEDA EN DX
MOV BL,AL
MOV DL,BL
ADD DL, 30H
MOV AH, 02H
INT 21H
.EXIT

;-------OPERACIONES---------
SALTO PROC NEAR
    MOV AH,09H
    LEA DX,LINEA
    INT 21H
    
    MOV DL, 00H
    RET
    SALTO ENDP

LEER PROC  NEAR
    MOV AH, 01H  ;LEER UN CARACTER DESDE EL TECLADO
    INT 21H ;LEE PRIMER CARACTER
    RET 
    LEER ENDP

LIMPIA PROC NEAR
    MOV AH, 00H
    MOV AL, 03H
    INT 10H
    RET
    LIMPIA ENDP

END

 



                                                  
                                                   
